# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-27 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='post',
            field=models.ManyToManyField(through='users.UserPost', to='users.Post', verbose_name='职位'),
        ),
    ]
